apiVersion: v1
kind: ReplicationController
metadata:
  name: discoveryrc
  namespace: default
spec:
  replicas: 1
  selector:
    app: discoveryrc
  template:
    metadata:
      name: discoveryrc
      labels:
        app: discoveryrc
      namespace: default
    spec:
      containers:
        - name: discoveryrc
          image: foxcloud.registry.com:8443/foxcloud/fox-discovery:dev
          ports:
            - name: server-port
              containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: development
          imagePullPolicy: Always
      imagePullSecrets:
        - name: myregistrykey
